# Generated by Django 4.2.30 on 2026-05-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='scholarships/')),
                ('description', models.TextField()),
                ('eligibility', models.TextField(blank=True)),
                ('amount', models.CharField(blank=True, max_length=120)),
                ('level', models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('artisan', 'Artisan'), ('higher_diploma', 'Higher Diploma')], max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('apply_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
