# Generated by Django 4.2.7 on 2026-05-11 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Describe your project in detail.')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated concise summary of the project.')),
                ('ai_expanded', models.TextField(blank=True, help_text='AI-expanded detailed write-up of the project.')),
                ('course_area', models.CharField(choices=[('engineering', 'Engineering & Technology'), ('ict', 'ICT & Computing'), ('construction', 'Building & Construction'), ('automotive', 'Automotive & Transport'), ('electrical', 'Electrical & Electronics'), ('hospitality', 'Hospitality & Tourism'), ('agriculture', 'Agriculture & Food'), ('health', 'Health & Social Care'), ('business', 'Business & Commerce'), ('creative', 'Creative Arts & Fashion'), ('other', 'Other')], default='other', max_length=50)),
                ('technologies', models.TextField(blank=True, help_text='Comma-separated tools, materials, or technologies used.')),
                ('status', models.CharField(choices=[('concept', 'Concept / Idea'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deployed', 'Deployed / In Use')], default='completed', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='showcase_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 – Needs significant improvement'), (2, '2 – Below expectations'), (3, '3 – Meets expectations'), (4, '4 – Exceeds expectations'), (5, '5 – Outstanding')])),
                ('practical_skills', models.PositiveSmallIntegerField(choices=[(1, '1 – Needs significant improvement'), (2, '2 – Below expectations'), (3, '3 – Meets expectations'), (4, '4 – Exceeds expectations'), (5, '5 – Outstanding')], default=3)),
                ('theoretical_knowledge', models.PositiveSmallIntegerField(choices=[(1, '1 – Needs significant improvement'), (2, '2 – Below expectations'), (3, '3 – Meets expectations'), (4, '4 – Exceeds expectations'), (5, '5 – Outstanding')], default=3)),
                ('creativity', models.PositiveSmallIntegerField(choices=[(1, '1 – Needs significant improvement'), (2, '2 – Below expectations'), (3, '3 – Meets expectations'), (4, '4 – Exceeds expectations'), (5, '5 – Outstanding')], default=3)),
                ('professionalism', models.PositiveSmallIntegerField(choices=[(1, '1 – Needs significant improvement'), (2, '2 – Below expectations'), (3, '3 – Meets expectations'), (4, '4 – Exceeds expectations'), (5, '5 – Outstanding')], default=3)),
                ('feedback', models.TextField(help_text='Detailed feedback and guidance for the trainee.')),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('recommended_for_freelance', models.BooleanField(default=False)),
                ('recommended_for_mentorship', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='projects.project')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'user_type': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('top_rated', 'Top Rated Trainee'), ('best_project', 'Best Project'), ('most_hired', 'Most Hired'), ('star_graduate', 'Star Graduate'), ('innovation', 'Innovation Award'), ('trainer_pick', "Trainer's Pick")], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
