# Generated by Django 4.2.30 on 2026-05-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerevaluation',
            name='creativity',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Needs significant improvement'), (2, '2 - Below expectations'), (3, '3 - Meets expectations'), (4, '4 - Exceeds expectations'), (5, '5 - Outstanding')], default=3),
        ),
        migrations.AlterField(
            model_name='trainerevaluation',
            name='practical_skills',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Needs significant improvement'), (2, '2 - Below expectations'), (3, '3 - Meets expectations'), (4, '4 - Exceeds expectations'), (5, '5 - Outstanding')], default=3),
        ),
        migrations.AlterField(
            model_name='trainerevaluation',
            name='professionalism',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Needs significant improvement'), (2, '2 - Below expectations'), (3, '3 - Meets expectations'), (4, '4 - Exceeds expectations'), (5, '5 - Outstanding')], default=3),
        ),
        migrations.AlterField(
            model_name='trainerevaluation',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Needs significant improvement'), (2, '2 - Below expectations'), (3, '3 - Meets expectations'), (4, '4 - Exceeds expectations'), (5, '5 - Outstanding')]),
        ),
        migrations.AlterField(
            model_name='trainerevaluation',
            name='theoretical_knowledge',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Needs significant improvement'), (2, '2 - Below expectations'), (3, '3 - Meets expectations'), (4, '4 - Exceeds expectations'), (5, '5 - Outstanding')], default=3),
        ),
    ]
