# Generated by Django 4.2.7 on 2026-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='trainer_department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='trainer_expertise',
            field=models.TextField(blank=True, help_text='Comma-separated expertise areas'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='trainer_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='trainer_years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student/Graduate'), ('trainer', 'Trainer/Evaluator'), ('company', 'Company'), ('individual', 'Individual')], default='student', max_length=20),
        ),
    ]
