# Generated by Django 4.2.7 on 2026-05-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentuser_trainer_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='achievements',
            field=models.TextField(blank=True, help_text='Awards, competitions, or notable achievements'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='certifications',
            field=models.TextField(blank=True, help_text='List any certifications or short courses completed'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='expected_salary',
            field=models.CharField(blank=True, help_text='Expected salary or rate range', max_length=100),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or student ID', max_length=50),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages spoken, comma-separated', max_length=255),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='preferred_job_type',
            field=models.CharField(blank=True, help_text='e.g. Full-time, Part-time, Attachment', max_length=100),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='references',
            field=models.TextField(blank=True, help_text='Name, title, and contact of a reference'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='work_experience',
            field=models.TextField(blank=True, help_text='Brief work or attachment experience'),
        ),
    ]
